[2025-04-25 09:44:50,814] - INFO - debug_pipeline - ========== Launching Data Ingestion Pipeline ==========
[2025-04-25 09:44:50,823] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-25 09:44:50,830] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-25 09:44:50,834] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-25 09:44:50,836] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-25 09:44:50,836] - INFO - data_ingestion_pipeline - ========== Data Ingestion Stage Started ==========
[2025-04-25 09:44:50,836] - INFO - data_ingestion - ========== Starting Data Ingestion ==========
[2025-04-25 09:44:51,010] - INFO - mongodb_handler - MongoClient initialized.
[2025-04-25 09:44:55,951] - INFO - mongodb_handler - Exported 22110 documents from network_security_db.phishing_records as DataFrame.
[2025-04-25 09:44:56,030] - INFO - mongodb_handler - MongoClient connection closed.
[2025-04-25 09:44:56,030] - INFO - data_ingestion - Fetched 22110 raw rows from data source.
[2025-04-25 09:44:56,031] - INFO - core - Created directory for Raw Data: 'artifacts/2025_04_25T08_44_48Z/data_ingestion/featurestore'
[2025-04-25 09:44:56,126] - INFO - core - Raw Data saved to: 'artifacts/2025_04_25T08_44_48Z/data_ingestion/featurestore/raw_data.csv'
[2025-04-25 09:44:56,126] - INFO - core - Directory already exists for Raw Data: 'data/raw'
[2025-04-25 09:44:56,222] - INFO - core - Raw Data saved to: 'data/raw/raw_data.csv'
[2025-04-25 09:44:56,225] - INFO - data_ingestion - Raw DataFrame cleaned successfully.
[2025-04-25 09:44:56,225] - INFO - core - Created directory for Cleaned (Ingested) Data: 'artifacts/2025_04_25T08_44_48Z/data_ingestion/ingested'
[2025-04-25 09:44:56,299] - INFO - core - Cleaned (Ingested) Data saved to: 'artifacts/2025_04_25T08_44_48Z/data_ingestion/ingested/ingested_data.csv'
[2025-04-25 09:44:56,299] - INFO - data_ingestion - ========== Data Ingestion Completed ==========
[2025-04-25 09:44:56,304] - INFO - data_ingestion_pipeline - Data Ingestion Process Completed.

Data Ingestion Artifact:
  - Raw Artifact:         'artifacts/2025_04_25T08_44_48Z/data_ingestion/featurestore/raw_data.csv'
  - Raw DVC Path:         'data/raw/raw_data.csv'
  - Ingested Data Path:   'artifacts/2025_04_25T08_44_48Z/data_ingestion/ingested/ingested_data.csv'

[2025-04-25 09:44:56,304] - INFO - data_ingestion_pipeline - ========== Data Ingestion Stage Completed ==========
[2025-04-25 09:44:56,304] - INFO - debug_pipeline - ========== Data Ingestion Pipeline Finished ==========
[2025-04-25 09:44:56,304] - INFO - debug_pipeline - ======================================================
[2025-04-25 09:44:56,304] - INFO - debug_pipeline - ========== Launching Data Validation Pipeline ==========
[2025-04-25 09:44:56,309] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-25 09:44:56,318] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-25 09:44:56,321] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-25 09:44:56,321] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-25 09:44:56,321] - INFO - data_validation_pipeline - ========= Data Validation Stage Started =========
[2025-04-25 09:44:56,355] - INFO - core - Ingested Data loaded from: 'artifacts/2025_04_25T08_44_48Z/data_ingestion/ingested/ingested_data.csv'
[2025-04-25 09:44:56,393] - INFO - core - Validated Base Data loaded from: 'data/validated/validated_data.csv'
[2025-04-25 09:44:56,393] - INFO - data_validation - Running data validation...
[2025-04-25 09:44:56,393] - INFO - data_validation - Schema hash check passed.
[2025-04-25 09:44:56,393] - INFO - core - Created directory for Missing Value Report: 'artifacts/2025_04_25T08_44_48Z/data_validation/reports'
[2025-04-25 09:44:56,393] - INFO - core - Missing Value Report saved to: 'artifacts/2025_04_25T08_44_48Z/data_validation/reports/missing_values_report.json'
[2025-04-25 09:44:56,407] - INFO - core - Directory already exists for Duplicates Report: 'artifacts/2025_04_25T08_44_48Z/data_validation/reports'
[2025-04-25 09:44:56,407] - INFO - core - Duplicates Report saved to: 'artifacts/2025_04_25T08_44_48Z/data_validation/reports/duplicates_report.yaml'
[2025-04-25 09:44:56,433] - INFO - core - Directory already exists for Drift Result: 'artifacts/2025_04_25T08_44_48Z/data_validation/reports'
[2025-04-25 09:44:56,441] - INFO - core - Drift Result saved to: 'artifacts/2025_04_25T08_44_48Z/data_validation/reports/drift_report.yaml'
[2025-04-25 09:44:56,443] - INFO - core - Directory already exists for Validation Report: 'artifacts/2025_04_25T08_44_48Z/data_validation/reports'
[2025-04-25 09:44:56,444] - INFO - core - Validation Report saved to: 'artifacts/2025_04_25T08_44_48Z/data_validation/reports/validation_report.yaml'
[2025-04-25 09:44:56,444] - INFO - core - Created directory for Validated Data: 'artifacts/2025_04_25T08_44_48Z/data_validation/validated'
[2025-04-25 09:44:56,464] - INFO - core - Validated Data saved to: 'artifacts/2025_04_25T08_44_48Z/data_validation/validated/validated_data.csv'
[2025-04-25 09:44:56,464] - INFO - core - Directory already exists for Validated Data: 'data/validated'
[2025-04-25 09:44:56,485] - INFO - core - Validated Data saved to: 'data/validated/validated_data.csv'
[2025-04-25 09:44:56,485] - INFO - data_validation_pipeline - Data Validation Process Completed.

Data Validation Artifact:
  - Validated Data Path: 'artifacts/2025_04_25T08_44_48Z/data_validation/validated/validated_data.csv'
  - Validation Status:   'True'

[2025-04-25 09:44:56,485] - INFO - data_validation_pipeline - ========= Data Validation Stage Completed =========
[2025-04-25 09:44:56,486] - INFO - debug_pipeline - ========== Data Validation Pipeline Finished ==========
[2025-04-25 09:44:56,487] - INFO - debug_pipeline - ======================================================
[2025-04-25 09:44:56,487] - INFO - debug_pipeline - ========== Launching Data Transformation Pipeline ==========
[2025-04-25 09:44:56,490] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-25 09:44:56,491] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-25 09:44:56,501] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-25 09:44:56,504] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-25 09:44:56,504] - INFO - data_transformation_pipeline - ========== Data Transformation Stage Started ==========
[2025-04-25 09:44:56,529] - INFO - core - Validated Data loaded from: 'artifacts/2025_04_25T08_44_48Z/data_validation/validated/validated_data.csv'
[2025-04-25 09:44:56,529] - INFO - data_transformation - ========== Starting Data Transformation ==========
[2025-04-25 09:44:56,548] - INFO - core - Created directory for X Preprocessor Pipeline: 'artifacts/2025_04_25T08_44_48Z/data_transformation/preprocessor'
[2025-04-25 09:44:56,551] - INFO - core - X Preprocessor Pipeline saved to: 'artifacts/2025_04_25T08_44_48Z/data_transformation/preprocessor/x_preprocessor.joblib'
[2025-04-25 09:44:56,551] - INFO - core - Directory already exists for Y Preprocessor Pipeline: 'artifacts/2025_04_25T08_44_48Z/data_transformation/preprocessor'
[2025-04-25 09:44:56,552] - INFO - core - Y Preprocessor Pipeline saved to: 'artifacts/2025_04_25T08_44_48Z/data_transformation/preprocessor/y_preprocessor.joblib'
[2025-04-25 09:44:56,552] - INFO - core - Created directory for X_train: 'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/train'
[2025-04-25 09:44:56,553] - INFO - core - X_train saved to: 'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/train/x_train.npy'
[2025-04-25 09:44:56,553] - INFO - core - Directory already exists for X_train: 'data/transformed/train'
[2025-04-25 09:44:56,554] - INFO - core - X_train saved to: 'data/transformed/train/x_train.npy'
[2025-04-25 09:44:56,554] - INFO - core - Directory already exists for y_train: 'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/train'
[2025-04-25 09:44:56,554] - INFO - core - y_train saved to: 'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/train/y_train.npy'
[2025-04-25 09:44:56,554] - INFO - core - Directory already exists for y_train: 'data/transformed/train'
[2025-04-25 09:44:56,554] - INFO - core - y_train saved to: 'data/transformed/train/y_train.npy'
[2025-04-25 09:44:56,556] - INFO - core - Created directory for X_val: 'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/val'
[2025-04-25 09:44:56,556] - INFO - core - X_val saved to: 'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/val/x_val.npy'
[2025-04-25 09:44:56,556] - INFO - core - Directory already exists for X_val: 'data/transformed/val'
[2025-04-25 09:44:56,556] - INFO - core - X_val saved to: 'data/transformed/val/x_val.npy'
[2025-04-25 09:44:56,556] - INFO - core - Directory already exists for y_val: 'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/val'
[2025-04-25 09:44:56,558] - INFO - core - y_val saved to: 'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/val/y_val.npy'
[2025-04-25 09:44:56,558] - INFO - core - Directory already exists for y_val: 'data/transformed/val'
[2025-04-25 09:44:56,558] - INFO - core - y_val saved to: 'data/transformed/val/y_val.npy'
[2025-04-25 09:44:56,558] - INFO - core - Created directory for X_test: 'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/test'
[2025-04-25 09:44:56,558] - INFO - core - X_test saved to: 'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/test/x_test.npy'
[2025-04-25 09:44:56,558] - INFO - core - Directory already exists for X_test: 'data/transformed/test'
[2025-04-25 09:44:56,558] - INFO - core - X_test saved to: 'data/transformed/test/x_test.npy'
[2025-04-25 09:44:56,558] - INFO - core - Directory already exists for y_test: 'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/test'
[2025-04-25 09:44:56,558] - INFO - core - y_test saved to: 'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/test/y_test.npy'
[2025-04-25 09:44:56,558] - INFO - core - Directory already exists for y_test: 'data/transformed/test'
[2025-04-25 09:44:56,558] - INFO - core - y_test saved to: 'data/transformed/test/y_test.npy'
[2025-04-25 09:44:56,562] - INFO - data_transformation - ========== Data Transformation Completed ==========
[2025-04-25 09:44:56,562] - INFO - data_transformation_pipeline - Data Transformation Completed Successfully: 
Data Transformation Artifact:
  - X-Train Data Path:    'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/train/x_train.npy'
  - Y-Train Data Path:    'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/train/y_train.npy'
  - X-Val Data Path:      'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/val/x_val.npy'
  - Y-Val Data Path:      'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/val/y_val.npy'
  - X-Test Data Path:     'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/test/x_test.npy'
  - Y-Test Data Path:     'artifacts/2025_04_25T08_44_48Z/data_transformation/transformed/test/y_test.npy'

[2025-04-25 09:44:56,562] - INFO - data_transformation_pipeline - ========== Data Transformation Stage Completed ==========
[2025-04-25 09:44:56,562] - INFO - debug_pipeline - ========== Data Transformation Pipeline Finished ==========
[2025-04-25 09:44:56,562] - INFO - debug_pipeline - ======================================================
[2025-04-25 09:44:56,562] - INFO - debug_pipeline - ========== Launching Model Trainer Pipeline ==========
[2025-04-25 09:44:56,564] - INFO - core - YAML loaded successfully from: 'config/config.yaml'
[2025-04-25 09:44:56,573] - INFO - core - YAML loaded successfully from: 'config/params.yaml'
[2025-04-25 09:44:56,575] - INFO - core - YAML loaded successfully from: 'config/schema.yaml'
[2025-04-25 09:44:56,579] - INFO - core - YAML loaded successfully from: 'config/templates.yaml'
[2025-04-25 09:44:56,580] - INFO - model_trainer_pipeline - ========== Model Training Stage Started ==========
[2025-04-25 09:44:56,580] - INFO - model_trainer - Initializing ModelTrainer with root_dir=artifacts\2025_04_25T08_44_48Z\model_trainer
[2025-04-25 09:44:57,762] - INFO - model_trainer - ========== Starting Model Training ==========
[2025-04-25 09:45:41,377] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py], line [147], message: [NetworkModel.from_objects() got an unexpected keyword argument 'x_preprocessor_path']
[2025-04-25 09:45:41,377] - ERROR - model_trainer_pipeline - Model Training Stage Failed
Traceback (most recent call last):
  File "E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py", line 147, in run_training
    network_model = NetworkModel.from_objects(
TypeError: NetworkModel.from_objects() got an unexpected keyword argument 'x_preprocessor_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\MyProjects\networksecurity\src\networksecurity\pipeline\model_trainer_pipeline.py", line 40, in run
    trainer_artifact = trainer.run_training()
  File "E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py", line 165, in run_training
    raise NetworkSecurityError(e, logger)
src.networksecurity.exception.exception.NetworkSecurityError: Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py], line [147], message: [NetworkModel.from_objects() got an unexpected keyword argument 'x_preprocessor_path']
[2025-04-25 09:45:41,377] - ERROR - exception - Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\pipeline\model_trainer_pipeline.py], line [40], message: [Error occurred in file [E:\MyProjects\networksecurity\src\networksecurity\components\model_trainer.py], line [147], message: [NetworkModel.from_objects() got an unexpected keyword argument 'x_preprocessor_path']]
